package com.light.project.szafc.common.entity.file;
/*
 * Automatically generated by jrpcgen 1.1.1 on 15-4-17 下午5:05
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
/**
 * Enumeration (collection of constants).
 */
public interface TFileHeaderTag {

    public static final int FILE_HEADER_TRANSACTION = 1;

}
// End of TFileHeaderTag.java
