package com.light.project.szafc.common.entity.file;
/*
 * Automatically generated by jrpcgen 1.1.1 on 15-4-17 下午5:05
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;

import com.light.common.xdr.entity.TU16;
import com.light.common.xdr.entity.TU32;
import com.light.common.xdr.entity.TU8;


import java.io.IOException;

public class TSJTSale implements XdrAble {
    private TU32 operatorID;
    private TU32 BOMShiftID;
    private TU32 transactionValue;
    private TU32 mediaType;
    private TU8 paymentmeans;
    // 需要注意！！！
    private TU16 duration;

    public TU32 getOperatorID() {
		return operatorID;
	}

	public void setOperatorID(TU32 operatorID) {
		this.operatorID = operatorID;
	}

	public TU32 getBOMShiftID() {
		return BOMShiftID;
	}

	public void setBOMShiftID(TU32 bOMShiftID) {
		BOMShiftID = bOMShiftID;
	}

	public TU32 getTransactionValue() {
		return transactionValue;
	}

	public void setTransactionValue(TU32 transactionValue) {
		this.transactionValue = transactionValue;
	}

	public TU32 getMediaType() {
		return mediaType;
	}

	public void setMediaType(TU32 mediaType) {
		this.mediaType = mediaType;
	}

	public TU8 getPaymentmeans() {
		return paymentmeans;
	}

	public void setPaymentmeans(TU8 paymentmeans) {
		this.paymentmeans = paymentmeans;
	}

	public TU16 getDuration() {
		return duration;
	}

	public void setDuration(TU16 duration) {
		this.duration = duration;
	}

	public TSJTSale() {
    }

    public TSJTSale(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
    	operatorID.xdrEncode(xdr);
    	BOMShiftID.xdrEncode(xdr);
    	transactionValue.xdrEncode(xdr);
    	mediaType.xdrEncode(xdr);
    	paymentmeans.xdrEncode(xdr);
    	duration.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
    	operatorID = new TU32(xdr);
    	BOMShiftID = new TU32(xdr);
    	transactionValue = new TU32(xdr);
    	mediaType = new TU32(xdr);
    	paymentmeans = new TU8(xdr);
    	duration = new TU16(xdr);

    }

}
// End of SLEUDMSG_t.java
