package com.light.project.szafc.common.entity.file;
/*
 * Automatically generated by jrpcgen 1.1.1 on 15-4-17 下午5:05
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;

import com.light.common.xdr.entity.TU32;
import com.light.common.xdr.entity.TU8;


import java.io.IOException;

public class TSLESJTUD implements XdrAble {
    private TU8 transactionType;
    private TTicketComm ticketComm;
    private TSJTSale SJTSale;
    

    public TU8 getTransactionType() {
		return transactionType;
	}

	public void setTransactionType(TU8 transactionType) {
		this.transactionType = transactionType;
	}

	public TTicketComm getTicketComm() {
		return ticketComm;
	}

	public void setTicketComm(TTicketComm ticketComm) {
		this.ticketComm = ticketComm;
	}

	public TSJTSale getSJTSale() {
		return SJTSale;
	}

	public void setSJTSale(TSJTSale sJTSale) {
		SJTSale = sJTSale;
	}

	public TSLESJTUD() {
    }

    public TSLESJTUD(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
    	transactionType.xdrEncode(xdr);
    	ticketComm.xdrEncode(xdr);
    	SJTSale.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
    	transactionType = new TU8(xdr);
    	ticketComm = new TTicketComm(xdr);
    	SJTSale = new TSJTSale(xdr);
    }

}
// End of SLEUDMSG_t.java
