package com.light.project.szafc.common.entity.file;
/*
 * Automatically generated by jrpcgen 1.1.1 on 15-4-17 下午5:05
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;

import com.light.common.xdr.entity.TU8;


import java.io.IOException;

public class TSLEMessage implements XdrAble {
	private Integer transactionTag;
	private TSLEUDMSG [] UD;

    public Integer getTransactionTag() {
		return transactionTag;
	}

	public void setTransactionTag(Integer transactionTag) {
		this.transactionTag = transactionTag;
	}

	public TSLEUDMSG[] getUD() {
		return UD;
	}

	public void setUD(TSLEUDMSG[] uD) {
		UD = uD;
	}

	public TSLEMessage() {
    }

    public TSLEMessage(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(transactionTag);
        switch ( transactionTag ) {
        case TFileHeaderTag.FILE_HEADER_TRANSACTION:
            { int $size = UD.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { UD[$idx].xdrEncode(xdr); } }
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
    	transactionTag = xdr.xdrDecodeInt();
        switch ( transactionTag ) {
        case TFileHeaderTag.FILE_HEADER_TRANSACTION:
            { int $size = xdr.xdrDecodeInt(); UD = new TSLEUDMSG[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { UD[$idx] = new TSLEUDMSG(xdr); } }
            break;
        }
    }

}
// End of SLEMessage_t.java
