package com.light.project.szafc.common.entity.file;
/*
 * Automatically generated by jrpcgen 1.1.1 on 15-4-17 下午5:05
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;

import com.light.common.xdr.entity.TU16;
import com.light.common.xdr.entity.TU32;

import java.io.IOException;

public class TSLEUDMSG implements XdrAble {
    private TSLESJTUD SJTUDData;
    private TUDComm UDComm;
    private TU32 UDSN;
    private TU16 businessDay;
    private TU32 TAC;

    public TSLESJTUD getSJTUDData() {
		return SJTUDData;
	}

	public void setSJTUDData(TSLESJTUD sJTUDData) {
		SJTUDData = sJTUDData;
	}

	public TUDComm getUDComm() {
		return UDComm;
	}

	public void setUDComm(TUDComm uDComm) {
		UDComm = uDComm;
	}

	public TU32 getUDSN() {
		return UDSN;
	}

	public void setUDSN(TU32 uDSN) {
		UDSN = uDSN;
	}

	public TU16 getBusinessDay() {
		return businessDay;
	}

	public void setBusinessDay(TU16 businessDay) {
		this.businessDay = businessDay;
	}

	public TU32 getTAC() {
		return TAC;
	}

	public void setTAC(TU32 tAC) {
		TAC = tAC;
	}

	public TSLEUDMSG() {
    }

    public TSLEUDMSG(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
    	SJTUDData.xdrEncode(xdr);
    	UDComm.xdrEncode(xdr);
    	UDSN.xdrEncode(xdr);
    	businessDay.xdrEncode(xdr);
    	TAC.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
    	SJTUDData = new TSLESJTUD(xdr);
    	UDComm = new TUDComm(xdr);
    	UDSN = new TU32(xdr);
    	businessDay = new TU16(xdr);
    	TAC = new TU32(xdr);
    }

}
// End of SLEUDMSG_t.java
