package com.light.project.szafc.common.entity.file;
/*
 * Automatically generated by jrpcgen 1.1.1 on 15-4-17 下午5:05
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;

import com.light.common.xdr.entity.TU16;
import com.light.common.xdr.entity.TU32;
import com.light.common.xdr.entity.TU64;
import com.light.common.xdr.entity.TU8;




import java.io.IOException;

public class TTicketComm implements XdrAble {
	private TU8 ticketType;
	private TU64 ticketlogicalID;
    private TU64 ticketPhyID;
    private TU8 testFlag;
    private TU32 ticketSAMID;
    private TU32 ticketSN;
    private TU16 ePurseSN;
    private TU16 startValidDate;
    private TU16 endValidDate;
	
	public TU8 getTicketType() {
		return ticketType;
	}

	public void setTicketType(TU8 ticketType) {
		this.ticketType = ticketType;
	}

	public TU64 getTicketlogicalID() {
		return ticketlogicalID;
	}

	public void setTicketlogicalID(TU64 ticketlogicalID) {
		this.ticketlogicalID = ticketlogicalID;
	}

	public TU64 getTicketPhyID() {
		return ticketPhyID;
	}

	public void setTicketPhyID(TU64 ticketPhyID) {
		this.ticketPhyID = ticketPhyID;
	}

	public TU8 getTestFlag() {
		return testFlag;
	}

	public void setTestFlag(TU8 testFlag) {
		this.testFlag = testFlag;
	}

	public TU32 getTicketSAMID() {
		return ticketSAMID;
	}

	public void setTicketSAMID(TU32 ticketSAMID) {
		this.ticketSAMID = ticketSAMID;
	}

	public TU32 getTicketSN() {
		return ticketSN;
	}

	public void setTicketSN(TU32 ticketSN) {
		this.ticketSN = ticketSN;
	}

	public TU16 getePurseSN() {
		return ePurseSN;
	}

	public void setePurseSN(TU16 ePurseSN) {
		this.ePurseSN = ePurseSN;
	}

	public TU16 getStartValidDate() {
		return startValidDate;
	}

	public void setStartValidDate(TU16 startValidDate) {
		this.startValidDate = startValidDate;
	}

	public TU16 getEndValidDate() {
		return endValidDate;
	}

	public void setEndValidDate(TU16 endValidDate) {
		this.endValidDate = endValidDate;
	}

	
    
    
    

    public TTicketComm() {
    }

    public TTicketComm(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
    	ticketType.xdrEncode(xdr);
    	ticketlogicalID.xdrEncode(xdr);
    	ticketPhyID.xdrEncode(xdr);
    	testFlag.xdrEncode(xdr);
    	ticketSAMID.xdrEncode(xdr);
    	ticketSN.xdrEncode(xdr);
    	ePurseSN.xdrEncode(xdr);
    	startValidDate.xdrEncode(xdr);
    	endValidDate.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
    	ticketType = new TU8(xdr);
    	ticketlogicalID = new TU64(xdr);
    	ticketPhyID = new TU64(xdr);
    	testFlag = new TU8(xdr);
    	ticketSAMID = new TU32(xdr);
    	ticketSN = new TU32(xdr);
    	ePurseSN = new TU16(xdr);
    	startValidDate = new TU16(xdr);
    	endValidDate = new TU16(xdr);
    	
    }

}
// End of SLEUDMSG_t.java
