package com.light.project.szafc.common.entity.file;
/*
 * Automatically generated by jrpcgen 1.1.1 on 15-4-17 下午5:05
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;

import com.light.common.xdr.entity.TU16;
import com.light.common.xdr.entity.TU32;
import com.light.common.xdr.entity.TU8;


import java.io.IOException;

public class TUDComm implements XdrAble {
    private TU8 transactionType;
    private TSZAFCTime64 transactionDateTime;
    private TU32 TACSAMID;
    private TU8 lineID;
    private TU16 stationID;
    private TU32 deviceID;
    private TU8 modeCode;
    private TU32 SAMUDSN;

    public TU8 getTransactionType() {
		return transactionType;
	}

	public void setTransactionType(TU8 transactionType) {
		this.transactionType = transactionType;
	}

	public TSZAFCTime64 getTransactionDateTime() {
		return transactionDateTime;
	}

	public void setTransactionDateTime(TSZAFCTime64 transactionDateTime) {
		this.transactionDateTime = transactionDateTime;
	}

	public TU32 getTACSAMID() {
		return TACSAMID;
	}

	public void setTACSAMID(TU32 tACSAMID) {
		TACSAMID = tACSAMID;
	}

	public TU8 getLineID() {
		return lineID;
	}

	public void setLineID(TU8 lineID) {
		this.lineID = lineID;
	}

	public TU16 getStationID() {
		return stationID;
	}

	public void setStationID(TU16 stationID) {
		this.stationID = stationID;
	}

	public TU32 getDeviceID() {
		return deviceID;
	}

	public void setDeviceID(TU32 deviceID) {
		this.deviceID = deviceID;
	}

	public TU8 getModeCode() {
		return modeCode;
	}

	public void setModeCode(TU8 modeCode) {
		this.modeCode = modeCode;
	}

	public TU32 getSAMUDSN() {
		return SAMUDSN;
	}

	public void setSAMUDSN(TU32 sAMUDSN) {
		SAMUDSN = sAMUDSN;
	}

	public TUDComm() {
    }

    public TUDComm(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
    	transactionType.xdrEncode(xdr);
    	transactionDateTime.xdrEncode(xdr);
    	TACSAMID.xdrEncode(xdr);
    	lineID.xdrEncode(xdr);
    	stationID.xdrEncode(xdr);
    	deviceID.xdrEncode(xdr);
    	modeCode.xdrEncode(xdr);
    	SAMUDSN.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
    	transactionType = new TU8(xdr);
    	transactionDateTime = new TSZAFCTime64(xdr);
    	TACSAMID = new TU32(xdr);
    	lineID = new TU8(xdr);
    	stationID = new TU16(xdr);
    	deviceID = new TU32(xdr);
    	modeCode = new TU8(xdr);
    	SAMUDSN = new TU32(xdr);
    }

}
// End of SLEUDMSG_t.java
